### ISSUE TITLE
日志文件句柄锁，直至文件解析到末尾

### ISSUE THREAD

**Issue by huapox** [johngcn/k8s-log#1]
@johngcn  您好， 细看了k8s-log的代码 甚是精辟~， log-agent基于监听来做日志的解析的， 结合log-pilot的官方"句柄保持机制"说明， 抛出一个问题，本人对golang并不专精，劳请做这下这方面的分析解答， 谢谢~

**如：** 之前的原日志文件追加频繁，解析能力有限文件还未解析到最新， 突然pod重启，日志被删，而这个事件刚好被捕获， 解除了文件监听。  这样是否会导致未解析的那部分日志丢失?

log-pilot说明URL:
https://yq.aliyun.com/articles/674327

**Comment by huapox** [comment]
**补充：** 
我这考虑以node为节点， emptyDir的方式做采集，非sidecar模式。 
感觉sidecar模式，pod重启时采集程序也会挂，直接导致重启期间可能有日志丢失的问题。

**Comment by gqcn** [comment]
@huapox 你好，`log-agent`是以`daemonset`模式运行的，POD重启时对应的Docker容器也会重启，无论如何`emptyDir`挂载的目录下的数据会被清空。不过可以通过K8S的HOOK机制来实现日志被清理之前允许执行一些的操作才让POD重启，但是相对来说会比较复杂。

**Comment by huapox** [comment]
@johngcn 感谢答复~

可否这样，不绕到业务pod那边，直接在**log-agent**采集时锁定日志文件来实现：
      daemonset模式以node节点为单位做采集的前提下， 
      log-agent读取日志时把已识别到的日志文件句柄锁定， 
      在收到文件删除事件时由当前解析offset 判断该日志文件是否解析完毕，来做解析收尾处理。

**Comment by gqcn** [comment]
@huapox 是的，目前`k8s-log`的`log-agent`就是这么做的，需要注意的是`k8s-log`这个项目虽然我们使用在生产中跑，但是仍然有一些小问题在不断完善。
